app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

app/main/urls.py
from django.urls import path
from .import views
from .models import Board, Thread, User, Post
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.index, name="index"),
    path('board<int:id>/', views.index_board, name="index_board"),
    path('thread<int:id>/', views.index_thread, name="index_thread"),
    path('user<str:username>/', views.index_user, name="index_user"),
    path('post_list/', views.index_posts, name="index_posts"),
    path('members_list/', views.index_users, name="index_users"),
    path('prescribed_conditions/', views.terms_and_conditions, name="terms_and_conditions"),
    path('register/', views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="main/login.html", extra_context={
                                                    'Threads': Thread.objects.all().order_by("Time_Created")[:10]}),
         name="login"),
    path('logout/', auth_views.LogoutView.as_view(next_page='/', extra_context={
                                                    'Threads': Thread.objects.all().order_by("Time_Created")[:10]}),
         name="logout"),
    #path('search/', views.index_post, name="search"),
]

app/main/models.py
from django.db import models
from django.contrib.auth.models import User


class Board(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Thread(models.Model):
    Tittle = models.CharField(max_length=150)
    Content = models.TextField(blank=False, null=False, max_length=10000)
    Time_Created = models.DateTimeField(auto_now_add=True)
    Board = models.ForeignKey(Board, on_delete=models.CASCADE)
    UserID = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.Tittle


class Post(models.Model):
    Content = models.CharField(blank=False, null=False, max_length=300)
    Time_Created = models.DateField(auto_now_add=True)
    UserID = models.ForeignKey(User, on_delete=models.CASCADE)
    ThreadID = models.ForeignKey(Thread, on_delete=models.CASCADE)

app/main/forms.py
import re
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from .models import Post, Thread


class RegistrationForm(forms.Form):
    username = forms.CharField(label='User name', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput())
    password2 = forms.CharField(label='repeat password', widget=forms.PasswordInput())

    def clean_password(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2 and password1:
                return password2
        raise forms.ValidationError('Неправильный пароль')

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Имя учетной записи не может содержать специальные символы')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Аккаунт уже существует')

    def save(self):
        User.objects.create_user(username= self.cleaned_data['username'], email=self.cleaned_data['email'], password=self.cleaned_data['password1'])


class CommentForm(forms.ModelForm):
    def __int__(self, *args, **kwargs):
        self.UserID = kwargs.pop('UserID', None)
        self.ThreadID = kwargs.pop('ThreadID', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        post = super().save(commit=False)
        post.UserID = self.UserID
        post.ThreadID = self.ThreadID
        post.save()

    class Meta:
        model = Post
        fields = ['Content']


class ThreadForm(forms.ModelForm):
    def __int__(self, *args, **kwargs):
        self.UserID = kwargs.pop('UserID', None)
        self.Board = kwargs.pop('Board', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        thread = super().save(commit=False)
        thread.UserID = self.UserID
        thread.Board = self.Board
        thread.save()

    class Meta:
        models = Thread
        fields = ['Tittle', 'Content']

app/main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Board, Thread, User, Post
from .forms import RegistrationForm, CommentForm, ThreadForm
from django.http import HttpResponseRedirect
from django.db.models import Q


def index(request):
    Data = {
        'Boards1': Board.objects.all()[:3],
        'Boards2': Board.objects.all()[3:9],
        'Boards3': Board.objects.all()[9:13],
        'Boards4': Board.objects.all()[13:16],
        'Boards5': Board.objects.all()[16:19],
        'Threads': Thread.objects.all().order_by("-Time_Created")[:10],
        'Users': User.objects.all()
    }
    return render(request, "main/index.html", Data)


def index_board(request, id):
    Boards = get_object_or_404(Board, pk=id)
    form = ThreadForm
    if request.method == 'POST':
        form = ThreadForm(request.POST, UserID=request.user, Board=Boards)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path)
    Data = {'Boards': Board.objects.get(pk=id), 'form': form, 'Threads': Thread.objects.all().order_by("-Time_Created")[:10]}
    return render(request, "main/index_board.html", Data)


def index_thread(request, id):
    thread = get_object_or_404(Thread, pk=id)
    form = CommentForm
    if request.method == 'POST':
        form = CommentForm(request.POST, UserID=request.user, ThreadID=thread)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path)
    Data = {'thread': thread, "form": form, 'Threads': Thread.objects.all().order_by("-Time_Created")[:10]}
    return render(request, "main/index_thread.html", Data)


def index_user(request, username):
    Data = {'User': User.objects.get(username=username), 'Threads': Thread.objects.all().order_by("-Time_Created")[:10]}
    return render(request, "main/index_user.html", Data)


def index_posts(request):
    thread = Thread.objects.all().order_by("-Time_Created")
    query = request.GET.get('q', None)
    if query is not None:
        thread = thread.filter(Q(Tittle__icontains=query) | Q(Content__icontains=query))
    Data = {'Thread': thread, 'Threads': Thread.objects.all().order_by("-Time_Created")[:10]}
    return render(request, "main/index_posts.html", Data)


def index_users(request):
    Data = {'User': User.objects.all().order_by("-date_joined"), 'Threads': Thread.objects.all().order_by("-Time_Created")[:10]}
    return render(request, "main/index_users.html", Data)


def terms_and_conditions(request):
    Data = {'Threads': Thread.objects.all().order_by("-Time_Created")[:10]}
    return render(request, "main/terms_and_conditions.html", Data)


def register(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    return render(request, "main/register.html", {'form': form, 'Threads': Thread.objects.all().order_by("-Time_Created")[:10]})

app/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'main/CSS/1.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background:#CACACA url({% static 'main/images/Background.png' %}) repeat-x top left">
    <header>
        <a href="/" id="logo"><img src="{% static 'main/images/Logo.png' %}" alt="Logo" width="100px" height="100px"></a>
    </header>

    <div id="global">
        <div id="nav">
            {% if user.username %}
                <section>
                    <img id="file-icon" src="{% static 'main/images/file.png' %}" alt="file-icon" height="20px" width="20px">
                    <p id="p1">Tech Forum</p>
                    <p id="greeting">Hello <a href="">{{user.username}}</a></p>
                    <nav>
                        <table id="nav-table" style="width: 100%">
                            <tr align="center">
                                <td class="nav-td"><a href="{% url 'index_posts' %}">All Posts</a></td>
                                <td class="nav-td"><a href="{% url 'index_users' %}">Members List</a></td>
                                <td class="nav-td"><a href="{% url 'logout' %}">Logout</a></td>
                            </tr>
                        </table>
                    </nav>
                </section>
            {% else %}
                <section>
                    <img id="file-icon" src="{% static 'main/images/file.png' %}" alt="file-icon" height="20px" width="20px">
                    <p id="p1">Tech Forum</p>
                    <a href="{% url 'login' %}" id="greeting">Click here to log in</a>
                    <nav>
                        <table id="nav-table" style="width: 100%">
                            <tr align="center">
                                <td class="nav-td"><a href="{% url 'index_posts' %}">All Posts</a></td>
                                <td class="nav-td"><a href="{% url 'index_users' %}">Members List</a></td>
                                <td class="nav-td"><a href="{% url 'register' %}">Register</a></td>
                                <td class="nav-td"><a href="{% url 'login' %}">Log in</a></td>
                            </tr>
                        </table>
                    </nav>
                </section>
            {% endif %}
        </div>

        <div id="content">
            {% block content %}

            {% endblock %}

            <div id="aside">
                <div id="aside1">
                    <h1>Recent News</h1>
                    {% for thread in Threads %}
                        <a href="{% url 'index_thread' thread.id %}" >{{thread.Title}}</a><br>
                        <p class="author-description">Posted by <a href="{% url 'index_user' thread.UserID %}" class="link-hot">{{thread.UserID}}</a> - {{thread.Time_Created}}</p>
                    {% endfor %}
                </div>
            </div>
            <br>
        </div>

        <br>
        <center><a class="footer-link" href="/">Home</a> | <a class="footer-link" href=".">Back to Top</a> | <a class="footer-link" href="{% url 'terms_and_conditions' %}">Terms & Conditions</a> | <a class="footer-link" href="">Privacy Policy</a></center>
        <br>

    </div>

</body>
</html>

app/main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Main{% endblock %}

{% block content %}
    <div class="section">
        <div class="tableBoard">
            <div class="list_child">
                <table>
                    <tr><h1>About Us</h1></tr>
                    {% for board in Boards1 %}
                        <tr>
                            <img class="file-icon" src="{% static 'main/images/file.png' %}" alt="file-icon" height="20px" width="20px">
                            <a href="{% url 'index_board' board.id %}" style="margin-left: 5px" class="board-link">{{board.name}}</a>
                            <p>{{board.description}}</p>
                            <hr>
                        </tr>
                    {% endfor %}
                    <tr><h1>Hardware</h1></tr>
                    {% for board in Boards2 %}
                        <tr>
                            <img class="file-icon" src="{% static 'main/images/file.png' %}" alt="file-icon" height="20px" width="20px">
                            <a href="{% url 'index_board' board.id %}" style="margin-left: 5px" class="board-link">{{board.name}}</a>
                            <p>{{board.description}}</p>
                            <hr>
                        </tr>
                    {% endfor %}
                    <tr><h1>Software</h1></tr>
                    {% for board in Boards3 %}
                        <tr>
                            <img class="file-icon" src="{% static 'main/images/file.png' %}" alt="file-icon" height="20px" width="20px">
                            <a href="{% url 'index_board' board.id %}" style="margin-left: 5px" class="board-link">{{board.name}}</a>
                            <p>{{board.description}}</p>
                            <hr>
                        </tr>
                    {% endfor %}
                    <tr><h1>Security</h1></tr>
                    {% for board in Boards4 %}
                        <tr>
                            <img class="file-icon" src="{% static 'main/images/file.png' %}" alt="file-icon" height="20px" width="20px">
                            <a href="{% url 'index_board' board.id %}" style="margin-left: 5px" class "board-link">{{board.name}}</a>
                            <p>{{board.description}}</p>
                            <hr>
                        </tr>
                    {% endfor %}
                    <tr><h1>Mobile Phones</h1></tr>
                    {% for board in Boards5 %}
                        <tr>
                            <img class="file-icon" src="{% static 'main/images/file.png' %}" alt="file-icon" height="20px" width="20px">
                            <a href="{% url 'index_board' board.id %}" style="margin-left: 5px" class="board-link">{{board.name}}</a>
                            <p>{{board.description}}</p>
                            <hr>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

app/main/templates/main/index_board.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Thread{% endblock %}

{% block content %}
    <div class="section">
        <div class="thread-list">
            <div class="list-child">
                {% if user.username %}
                    <form action="" method="POST">
                        {% csrf_token %}
                        <p><label>Post a Thread</label></p>
                        <div>
                            Title
                            <br>
                            {{form.Title}}
                        </div>
                        <div>
                            Content <br>
                            {{form.Content}}
                        </div>
                        <br>
                        <input type="submit" value="Post">
                    </form>
                {% endif %}

                {% for item in Boards.thread_set.all %}
                    <img class="file-icon" src="{% static 'main/images/file.png' %}" alt="file-icon" height="20px" width="20px">
                    <a href="{% url 'index_thread' item.id %}">{{item.Title}}</a><br>
                    <p class="thread-description">posted by <a href="">{{item.UserID}}</a> - {{item.Time_Created}}</p>
                    <hr>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

app/main/templates/main/index_posts.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Thread{% endblock %}

{% block content %}
    <div class="section">
        <div class="list-child" style="margin-top:20px">
            <form action="" method="GET">
                <input type="text" name="q" placeholder="Search">
                <input type="submit" name="" id="" value="Search">
            </form>
            <h1>List of Posts</h1>
            {% for item in Thread %}
                <div class="post-list-item" style="background-color: #cccccc">
                    <div class="post-list-user" style="height: 60px; overflow: auto">
                        <p><a href="{% url 'index_thread' item.id %}">{{item.Title}}</a>:{{item.Content}}</p>
                    </div>
                    <p style="margin-left: 100px"><a href="{% url 'index_user' item.UserID %}">{{item.UserID}}</a>-{{item.Time_Created}}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/main/templates/main/index_thread.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Thread{% endblock %}

{% block content %}
    <div class="section">
        <div class="thread">
            <div class="list-child">
                <h1>{{thread.Title}}</h1>
                <p>{{thread.Content|safe|linebreaks}}</p>
                <p style="margin-left: 380px"><a class="link-hot" href="{% url 'index_user' thread.UserID %}">{{thread.UserID}}</a>-{{thread.Time_Created}}</p>
            </div>
        </div>

        <div class="comments">
            <h1>Comments:</h1>
            {% for item in thread.post_set.all %}
                <p><a class="link-hot" href="{% url 'index_user' item.UserID %}">{{item.UserID}}</a>:</p>
                <h3 style="margin-left: 30px">{{item.Content|linebreaks}}</h3>
                <p style="margin-left: 500px">{{item.Time_Created}}</p>
                <hr>
            {% endfor %}

            {% if user.username %}
                <form action="" method="POST">
                    {% csrf_token %}
                    <p><label >Comment</label></p>
                    {{form.Content}}
                    <br>
                    <input type="submit" value="Comment">
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

app/main/templates/main/index_user.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Thread{% endblock %}

{% block content %}
    <div class="section">
        <div class="list-child" style="margin-top:20px">
            <h1>List of Posts by {{User.username}}</h1>
            {% for item in User.thread_set.all %}
                <div class="user-post-item" style="background-color: #cccccc">
                    <div class="user-post" style="height: 60px; overflow: auto">
                        <p><a href="{% url 'index_thread' item.id %}">{{item.Title}}</a>:{{item.Content}}</p>
                    </div>
                    <p style="margin-left: 100px">{{item.Time_Created}}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/main/templates/main/index_users.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Thread{% endblock %}

{% block content %}
    <div class="section">
        <div class="list-child" style="margin-top:20px">
            <h1>List of Members</h1>
            <table style="width: 100%">
                <tr>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Join Date</th>
                </tr>
                {% for item in User %}
                    <tr>
                        <td><a href="{% url 'index_user' item.username %}">{{item.username}}</a></td>
                        <td>{{item.email}}</td>
                        <td>{{item.date_joined}}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

app/main/templates/main/login.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Thread{% endblock %}

{% block content %}
    <div class="section">
        <div class="thread-list">
            <form method="POST">
                {% csrf_token %}
                <br>
                <h1>Login</h1>
                {% for key, value in form.errors.items %}
                    {{value}}
                {% endfor %}
                <p><label>Username:</label>{{form.username}}</p>
                <p><label>Password:</label>{{form.password}}</p>
                <input type="hidden" name="next" value="/">
                <input type="submit" value="Login">
                <br>
            </form>
        </div>
    </div>
{% endblock %}

app/main/templates/main/register.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Thread{% endblock %}

{% block content %}
    <div class="section">
        <div class="thread-list">
            <div class="list-child">
                <form action="." method="POST">
                    {% csrf_token %}
                    <br>
                    <h1>Registration</h1>
                    {{form.as_p}}
                    <input type="submit" value="Register">
                    <br>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/main/templates/main/terms_and_conditions.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Thread{% endblock %}

{% block content %}
    <div class="section">
        <div class="list-child" style="margin-top:20px">
            <h1>Terms and Conditions</h1>
            <pre>
    This Agreement ("Agreement," "Terms") governing the provision and use of the Tech Forum
social network service ("Agreement," "Terms") is based on the Principles of SNS and
governs our relationship with users (members) and others interacting with Tech Forum and
its brands, products, and services, which we refer to as "Tech Forum Services" or "Services."
By using or accessing Tech Forum Services, you agree to this Agreement.

I. Purpose, Content – Terms of Use

1. Purpose and content of the service
- Tech Forum Social Network (Tech Forum) is where members share and exchange information
about science and technology trends, tools, scientific equipment, and technology.
- Tech Forum is a place where members introduce, learn, share, and exchange information
about new science and technology products on the Vietnamese and global market.

2. Terms of use
- To access and use Tech Forum Services, members must agree to and comply with the terms
set forth in this Agreement and the rules and regulations linked to, integrated, including.
- When accessing, using Tech Forum Services through any means (computer, phone, TV,
Internet-connected device), or using the Tech Forum application, members must also
comply with this Code of Conduct.
- To meet members' usage needs, Tech Forum continuously improves and develops, so the
terms provided in the Agreement for providing and using Tech Forum Services may be
updated, modified at any time without prior notice to members. Tech Forum will publicly
announce any changes and additions on the Website, forums about those changes.

II. Account registration and service usage

1. Members are responsible for their behavioral capacity when registering an account and
using Tech Forum. In case Internet users under 14 years of age want to register as
members, the legal guardian must agree and decide to register their personal information
to show consent and responsibility before the law for that registration.
2. After logging into the system, members can change their username. Usernames must
comply with the naming rules, must not violate any of the prohibitions of this Agreement.
3. Members must register, log in to use the Service, share information on Tech Forum. Each
member is allowed to register only 1 account on Tech Forum.
4. On the Tech Forum system's Website, there are links to other websites, or icons of other
websites, these websites are not under the control or ownership of Tech Forum. Accessing
to these links can be risky and dangerous. Members bear full risk when using these linked
websites. Tech Forum will not be responsible for the content of any website or destination
outside the Tech Forum website system.

III. Prohibited content exchange and sharing on the social network

When using Tech Forum's system's services, members are strictly prohibited from
performing some behaviors, including but not limited to the following:
1. Abuse of providing, exchanging, using information on Tech Forum for the purpose of:
- Opposing the Socialist Republic of Vietnam; causing harm to national security, social
order, and safety; disrupting the national solidarity; propagating invasive wars and
terrorism; inciting hatred, conflict between ethnic groups, races, religions.
- Propagating, inciting violence, sexual abuse, crime, social evils, superstitions, undermining
the national and cultural traditions of the nation.
- Absolutely not discussing, posting content on political issues.
2. Members are prohibited from using Tech Forum to reveal state secrets, military secrets,
security, economic, diplomatic, and other secrets stipulated by law in any form on the
Tech Forum website.
3. Advertising, promoting, buying and selling goods and services that are prohibited or
disseminating forbidden press, literature, art, banned publications on Tech Forum.
4. When communicating with other users, members harass, swear, ridicule, disturb or
be uncivilized.
5. Members have the right to use their own image. When using another person's image,
members must have that person's consent. Prohibiting the use of someone else's image
that violates their dignity, honor, and reputation.
6. Exploiting Tech Forum's social network to collect information about other members, publish
information, documents about the private life of other members.
7. Absolutely not discussing, posting content on political issues.
8. Banned from posting content that is false, offensive, derogatory, or derogatory to the
dignity, reputation, or legal interests of organizations and individuals.
9. Absolutely not discussing, posting content on political issues.
10. Abuse of the Tech Forum system to organize forms of gambling, gaming, or agreements
related to money, cash, or other objects. Sharing fshare, megashare, tenlua, itunes, mediafire
accounts.
11. Obstruction against the law, causing disturbances, destroying the server system; illegally
obstructing access to information and the legitimate use of services on Tech Forum.
12. Unlawful use of passwords, lock codes of organizations, individuals, personal
information, and Internet resources.
13. Directly or indirectly, using any means (such as computer programs, Internet-connected
devices, Internet-based web services, or other means) to remove, alter, bypass, evade, interfere
with, or damage any copyright, trademark, or other proprietary rights indicators on the Content
(such as logos) or any control measures, data protection devices, and other means to restrict
access from different geographical areas.
14. Directly or indirectly through any means (such as computer programs, web-based
services, web-based services, or other means) to copy, download, capture, reproduce, produce,
store, distribute, upload, publish, modify, translate, broadcast, display, sell, transmit or
retransmit the content.
15. Create, reproduce, distribute, or advertise any detail of any content without the consent
of Tech Forum. Members are not allowed to build business models using content, whether
for profit or not. The content referred to in Tech Forum includes, but is not limited to any
text, graphics, images, layouts, interfaces, icons, images, audio, and video material, and
static images. Furthermore, we prohibit the creation of derivative works or materials
originating from or based on any content, including video creation, video, wallpaper, greeting
cards, and merchandise.
16. Impersonate organizations, individuals and disseminate false information, false information
on Tech Forum that violates the legitimate rights and interests of organizations, individuals.
17. Create links to illegal domains of organizations, individuals. Create, install, distribute
harmful software, computer viruses; unlawfully interfere, take control of the information
system, create tools for attacks on the Internet.
18. Absolutely not use any programs, tools, or any other means to interfere with the Tech Forum
system.
19. Absolutely no interference with illegal logins or attempted illegal logins or damage to the
Tech Forum server system.
</pre>
        </div>
    </div>
    
    
{% endblock %}